# Generated by Django 5.0.2 on 2024-06-03 15:42

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_image),
        ),
    ]
