# Generated by Django 5.0.2 on 2024-06-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recived', 'Recived'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return requested', 'Return requested'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Succnessful'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recived', 'Recived'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return requested', 'Return requested'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
