# Generated by Django 5.0.2 on 2024-08-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catalogueimage',
            options={},
        ),
    ]
