# Generated by Django 5.0.2 on 2024-06-03 15:42

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.rename_image),
        ),
    ]
