# Generated by Django 5.0.2 on 2024-06-03 15:42

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_image),
        ),
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.rename_image),
        ),
    ]
